#!/usr/bin/env ruby

require 'optparse'
options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: ocelot [options]"

  opts.on("-n", "--line-numbers", "Add line numbers") do |ln|
    options[:line_numbers] = ln
  end

  opts.on("-b", "--non-blank-line-numbers", "Add line numbers for non-blank lines") do |ln|
    options[:line_numbers_non_blank] = ln
    options[:line_numbers] = ln
  end
  
  opts.on("-v", "--[no-]verbose", "Run verbosely") do |v|
    options[:verbose] = v
  end
end.parse!

if ARGV.empty?
  print ARGF.read
else
  given_files = ARGV.map(&:to_s)
  given_files.each do |file|
    if options[:line_numbers]
      idx = 1
      File.readlines(file).each do |line|
        if options[:line_numbers_non_blank] && line.strip.empty?
          print line
        else
          print ["#{idx}".rjust(6, " "), "\t", "#{line}"].join("")
          idx += 1
        end
      end
    else
      print File.read(file)  
    end
  end
end
